# 데이터분석 순서(KDD 분석 방법론)
* 데이터 세트 선택 : CSV, EXCEL, DB에서 데이터를 읽어옴
* 데이터 전처리 : 데이터타입, 결측값, 이상치탐지, 데이터분포분석, 상관관계
* 데이터 변환(특성 추출) : 원본 데이터에서 새로운 데이터 생성, 삭제, 스케일링, 구간화
* 데이터 마이닝(모델 만들기, 분석) : 분석에 적합한 알고리즘 선택, 모델 생성, 튜닝
* 결과 평가 : 테스트 데이터를 이용해서 데이터 마이닝으로 만든 모델의 성능 평가

# 데이터 전처리
* 데이터 타입 변환
* 결측치 탐지 및 보간
* 이상치 탐지 및 처리
* 데이터 특성 파악(치우침, 분포 특성)
* 변수들 간의 상관관계 분석

In [1]:
import pandas as pd
import numpy as np

# 1. 데이터 세트 선택 및 로딩
* 데이터 로드 후 head(), tail()로 컬럼과 데이터 파악

In [42]:
data = pd.read_csv("./data/Titanic_train.csv")
data.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

# 2. .info()로 컬럼명, 결측치, 데이터 타입 파악

In [3]:
# 데이터가 너무 커서 Non-Null이 표시 안될 때: show_counts=True
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

# 3. describe()로 기초통계량 확인

In [4]:
data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

# 4. 결측값 찾고, 비율 보고, 대치/삭제하기
* isna().sum() / len(데이터프레임) * 100
* 결측값 비율이 5% 미만: 행, 열을 제거, 분석에 크게 영향을 미치지 않음
* 결측값 비율이 5% ~ 30%: 결측값을 대체(imputation)
    * 수치형 데이터(숫자형, 나이, 가격): 평균(mean), 중앙값(median), 최빈값(mode)으로 대체
    * 범주형 데이터(문자형(숫자형), 선실등급, 탑승지): 최빈값(mode)로 대체
* 결측값 비율이 30% ~ 50%: 컬럼의 중요도에 따라서 결측값을 대체 혹은 삭제
    * KNN(K-Nearest Neighbor, 최근접이웃) imputer, 회귀분석을 통해 결측값 대체
* 결측값 비율이 50% 이상: 해당 컬럼 삭제

In [5]:
round(data.isna().sum() / len(data) * 100, 2)

PassengerId     0.00
Survived        0.00
Pclass          0.00
Name            0.00
Sex             0.00
Age            19.87
SibSp           0.00
Parch           0.00
Ticket          0.00
Fare            0.00
Cabin          77.10
Embarked        0.22
dtype: float64

## 결측 데이터의 종류
* MCAR(완전 무작위 결측): 다른 변수와 무관하게 생긴 결측(랜덤, 이유 없음)
    * 설문조사 중 일부 응답자가 무작위로 답변을 건너뜀
* MAR(무작위 결측): 다른 변수와는 관련 있지만 본인과는 무관
    * 나이가 많은 사람들이 소득란에 응답을 하지 않는 경우
    * 직업에 따라서 학력란에 응답하지 않는 경우
* NMAR(비무작위 결측): 변수 자기 자신과 직접 관련이 있는 경우
    * 소득이 낮은 사람이 자신의 소득을 숨기는 경우(소득과 결측이 직접 관련)
    * 체중이 많이 나가는 경우 자신의 체중을 숨기는 경우
    * 만족도가 낮은 고객이 만족도 조사에 응하지 않는 경우

## 결측치 처리방법
### 1) 단순대치법(simple imputation)
#### (1) 완전분석: 결측값이 있는 모든 행을 삭제하고 완전한 자료만으로 분석(잘 안씀)
* 결측값을 삭제해도 모델을 만들기에 충분히 많은 데이터가 있는 경우
* 결측값을 삭제한 후에 데이터에 편향이 없다는 전제가 있을 때
* dropna(): 결측값이 있는 모든 행 삭제

In [6]:
data.dropna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [7]:
183 / len(data) * 100

20.53872053872054

#### (2) 평균 대치법: 결측치가 있는 컬럼에서 데이터의 평균을 구한 후 결측값을 대치
* 평균을 이용하기 때문에 간편
* 데이터에 이상치가 있을 경우
* 데이터에 이상치가 있는 경우 중앙값이나 최빈값을 고려해야 한다.

In [8]:
a = pd.Series([24, 5, 10, 34, 20, 18, 28, 20])
b = pd.Series([24, 5, 10, 34, 20, 18, 28, 2000])

In [9]:
a.mean()

np.float64(19.875)

In [10]:
b.mean()

np.float64(267.375)

In [11]:
a.median()

np.float64(20.0)

In [12]:
b.median()

np.float64(22.0)

Age 컬럼의 결측값을 평균 대치법으로 대치

In [13]:
data['Age'].isna().sum()

np.int64(177)

In [14]:
data['Age'].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [15]:
age_na_idx = data[data['Age'].isna()].index

In [43]:
# 깊은 복사, 얕은 복사
data2 = data.copy()
data3 = data.copy()
data4 = data.copy()

In [17]:
data['Age'] = data['Age'].fillna(data['Age'].mean())

In [18]:
data.loc[age_na_idx]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,29.699118,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,29.699118,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,29.699118,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,29.699118,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,29.699118,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,29.699118,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,29.699118,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,29.699118,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,29.699118,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,NaN,S

중앙값으로 대치

In [19]:
age_na_index2 = data2[data2['Age'].isna()].index

In [20]:
data2['Age'] = data2['Age'].fillna(data2['Age'].median())

In [21]:
data2.loc[age_na_index2]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,28.0,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,28.0,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,28.0,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,28.0,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,28.0,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,28.0,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,28.0,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,28.0,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,28.0,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,NaN,S

In [22]:
data3['Age'].mode()

0    24.0
Name: Age, dtype: float64

In [23]:
print(type(data3['Age'].mode()))

<class 'pandas.core.series.Series'>

In [24]:
age_na_index3 = data3[data3['Age'].isna()].index

In [25]:
data3['Age'] = data3['Age'].fillna(data3['Age'].mode()[0])

In [26]:
data3.loc[age_na_index3]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,24.0,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,24.0,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,24.0,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,24.0,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,24.0,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,24.0,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,24.0,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,24.0,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,24.0,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,24.0,1,2,W./C. 6607,23.4500,NaN,S

# scikit-learn의 simple imputer를 이용한 대치

In [ ]:
data = pd.read_csv("./data/Titanic_train.csv")

In [ ]:
data2 = data.copy()
data3 = data.copy()
data4 = data.copy()

In [35]:
from sklearn.impute import SimpleImputer

In [44]:
imp_mean = SimpleImputer(strategy='mean')
data4['Age'] = imp_mean.fit_transform(data4[['Age']])[:, 0]

In [45]:
data4['Age'].isna().sum()

np.int64(0)

In [46]:
na_idx = data3[data3['Age'].isna()].index

In [47]:
imp_median = SimpleImputer(strategy='median')
data3['Age'] = imp_median.fit_transform(data3[['Age']])[:, 0]

In [48]:
data3.loc[na_idx]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,28.0,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,28.0,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,28.0,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,28.0,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,28.0,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,28.0,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,28.0,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,28.0,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,28.0,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,NaN,S

In [50]:
imp_mode = SimpleImputer(strategy='most_frequent')
data2['Age'] = imp_mode.fit_transform(data2[['Age']])[:, 0]

In [51]:
data2.loc[na_idx]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,24.0,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,24.0,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,24.0,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,24.0,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,24.0,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,24.0,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,24.0,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,24.0,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,24.0,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,24.0,1,2,W./C. 6607,23.4500,NaN,S

In [57]:
imp_mode = SimpleImputer(strategy='most_frequent')
print(imp_mode.fit_transform(data2[['Age']]).ndim)
print(imp_mode.fit_transform(data2[['Age']]).shape)
imp_mode.fit_transform(data2[['Age']])[:, 0]

2
(891, 1)

array([22.  , 38.  , 26.  , 35.  , 35.  , 24.  , 54.  ,  2.  , 27.  ,
       14.  ,  4.  , 58.  , 20.  , 39.  , 14.  , 55.  ,  2.  , 24.  ,
       31.  , 24.  , 35.  , 34.  , 15.  , 28.  ,  8.  , 38.  , 24.  ,
       19.  , 24.  , 24.  , 40.  , 24.  , 24.  , 66.  , 28.  , 42.  ,
       24.  , 21.  , 18.  , 14.  , 40.  , 27.  , 24.  ,  3.  , 19.  ,
       24.  , 24.  , 24.  , 24.  , 18.  ,  7.  , 21.  , 49.  , 29.  ,
       65.  , 24.  , 21.  , 28.5 ,  5.  , 11.  , 22.  , 38.  , 45.  ,
        4.  , 24.  , 24.  , 29.  , 19.  , 17.  , 26.  , 32.  , 16.  ,
       21.  , 26.  , 32.  , 25.  , 24.  , 24.  ,  0.83, 30.  , 22.  ,
       29.  , 24.  , 28.  , 17.  , 33.  , 16.  , 24.  , 23.  , 24.  ,
       29.  , 20.  , 46.  , 26.  , 59.  , 24.  , 71.  , 23.  , 34.  ,
       34.  , 28.  , 24.  , 21.  , 33.  , 37.  , 28.  , 21.  , 24.  ,
       38.  , 24.  , 47.  , 14.5 , 22.  , 20.  , 17.  , 21.  , 70.5 ,
       29.  , 24.  ,  2.  , 21.  , 24.  , 32.5 , 32.5 , 54.  , 12.  ,
       24.  , 24.  , 24.  , 45.  , 33.  , 20.  , 47.  , 29.  , 25.  ,
       23.  , 19.  , 37.  , 16.  , 24.  , 24.  , 22.  , 24.  , 19.  ,
       18.  , 19.  , 27.  ,  9.  , 36.5 , 42.  , 51.  , 22.  , 55.5 ,
       40.5 , 24.  , 51.  , 16.  , 30.  , 24.  , 24.  , 44.  , 40.  ,
       26.  , 17.  ,  1.  ,  9.  , 24.  , 45.  , 24.  , 28.  , 61.  ,
        4.  ,  1.  , 21.  , 56.  , 18.  , 24.  , 50.  , 30.  , 36.  ,
       24.  , 24.  ,  9.  ,  1.  ,  4.  , 24.  , 24.  , 45.  , 40.  ,
       36.  , 32.  , 19.  , 19.  ,  3.  , 44.  , 58.  , 24.  , 42.  ,
       24.  , 24.  , 28.  , 24.  , 34.  , 45.5 , 18.  ,  2.  , 32.  ,
       26.  , 16.  , 40.  , 24.  , 35.  , 22.  , 30.  , 24.  , 31.  ,
       27.  , 42.  , 32.  , 30.  , 16.  , 27.  , 51.  , 24.  , 38.  ,
       22.  , 19.  , 20.5 , 18.  , 24.  , 35.  , 29.  , 59.  ,  5.  ,
       24.  , 24.  , 44.  ,  8.  , 19.  , 33.  , 24.  , 24.  , 29.  ,
       22.  , 30.  , 44.  , 25.  , 24.  , 37.  , 54.  , 24.  , 29.  ,
       62.  , 30.  , 41.  , 29.  , 24.  , 30.  , 35.  , 50.  , 24.  ,
        3.  , 52.  , 40.  , 24.  , 36.  , 16.  , 25.  , 58.  , 35.  ,
       24.  , 25.  , 41.  , 37.  , 24.  , 63.  , 45.  , 24.  ,  7.  ,
       35.  , 65.  , 28.  , 16.  , 19.  , 24.  , 33.  , 30.  , 22.  ,
       42.  , 22.  , 26.  , 19.  , 36.  , 24.  , 24.  , 24.  , 23.5 ,
        2.  , 24.  , 50.  , 24.  , 24.  , 19.  , 24.  , 24.  ,  0.92,
       24.  , 17.  , 30.  , 30.  , 24.  , 18.  , 26.  , 28.  , 43.  ,
       26.  , 24.  , 54.  , 31.  , 40.  , 22.  , 27.  , 30.  , 22.  ,
       24.  , 36.  , 61.  , 36.  , 31.  , 16.  , 24.  , 45.5 , 38.  ,
       16.  , 24.  , 24.  , 29.  , 41.  , 45.  , 45.  ,  2.  , 24.  ,
       28.  , 25.  , 36.  , 24.  , 40.  , 24.  ,  3.  , 42.  , 23.  ,
       24.  , 15.  , 25.  , 24.  , 28.  , 22.  , 38.  , 24.  , 24.  ,
       40.  , 29.  , 45.  , 35.  , 24.  , 30.  , 60.  , 24.  , 24.  ,
       24.  , 25.  , 18.  , 19.  , 22.  ,  3.  , 24.  , 22.  , 27.  ,
       20.  , 19.  , 42.  ,  1.  , 32.  , 35.  , 24.  , 18.  ,  1.  ,
       36.  , 24.  , 17.  , 36.  , 21.  , 28.  , 23.  , 24.  , 22.  ,
       31.  , 46.  , 23.  , 28.  , 39.  , 26.  , 21.  , 28.  , 20.  ,
       34.  , 51.  ,  3.  , 21.  , 24.  , 24.  , 24.  , 33.  , 24.  ,
       44.  , 24.  , 34.  , 18.  , 30.  , 10.  , 24.  , 21.  , 29.  ,
       28.  , 18.  , 24.  , 28.  , 19.  , 24.  , 32.  , 28.  , 24.  ,
       42.  , 17.  , 50.  , 14.  , 21.  , 24.  , 64.  , 31.  , 45.  ,
       20.  , 25.  , 28.  , 24.  ,  4.  , 13.  , 34.  ,  5.  , 52.  ,
       36.  , 24.  , 30.  , 49.  , 24.  , 29.  , 65.  , 24.  , 50.  ,
       24.  , 48.  , 34.  , 47.  , 48.  , 24.  , 38.  , 24.  , 56.  ,
       24.  ,  0.75, 24.  , 38.  , 33.  , 23.  , 22.  , 24.  , 34.  ,
       29.  , 22.  ,  2.  ,  9.  , 24.  , 50.  , 63.  , 25.  , 24.  ,
       35.  , 58.  , 30.  ,  9.  , 24.  , 21.  , 55.  , 71.  , 21.  ,
       24.  , 54.  , 24.  , 25.  , 24.  , 17.  , 21.  , 24.  , 37.  ,
       16.  , 18.  , 33.  , 24.  , 28.  , 26.  , 29.  , 24.  , 36.  ,
       54.  , 24.  , 47.  , 34.  , 24.  , 36.  , 32.  , 30.  , 22.  ,
       24.  , 44.  , 24.  , 40.5 , 50.  , 24.  , 39.  , 23.  ,  2.  ,
       24.  , 17.  , 24.  , 30.  ,  7.  , 45.  , 30.  , 24.  , 22.  ,
       36.  ,  9.  , 11.  , 32.  , 50.  , 64.  , 19.  , 24.  , 33.  ,
        8.  , 17.  , 27.  , 24.  , 22.  , 22.  , 62.  , 48.  , 24.  ,
       39.  , 36.  , 24.  , 40.  , 28.  , 24.  , 24.  , 24.  , 19.  ,
       29.  , 24.  , 32.  , 62.  , 53.  , 36.  , 24.  , 16.  , 19.  ,
       34.  , 39.  , 24.  , 32.  , 25.  , 39.  , 54.  , 36.  , 24.  ,
       18.  , 47.  , 60.  , 22.  , 24.  , 35.  , 52.  , 47.  , 24.  ,
       37.  , 36.  , 24.  , 49.  , 24.  , 49.  , 24.  , 24.  , 24.  ,
       44.  , 35.  , 36.  , 30.  , 27.  , 22.  , 40.  , 39.  , 24.  ,
       24.  , 24.  , 35.  , 24.  , 34.  , 26.  ,  4.  , 26.  , 27.  ,
       42.  , 20.  , 21.  , 21.  , 61.  , 57.  , 21.  , 26.  , 24.  ,
       80.  , 51.  , 32.  , 24.  ,  9.  , 28.  , 32.  , 31.  , 41.  ,
       24.  , 20.  , 24.  ,  2.  , 24.  ,  0.75, 48.  , 19.  , 56.  ,
       24.  , 23.  , 24.  , 18.  , 21.  , 24.  , 18.  , 24.  , 24.  ,
       32.  , 23.  , 58.  , 50.  , 40.  , 47.  , 36.  , 20.  , 32.  ,
       25.  , 24.  , 43.  , 24.  , 40.  , 31.  , 70.  , 31.  , 24.  ,
       18.  , 24.5 , 18.  , 43.  , 36.  , 24.  , 27.  , 20.  , 14.  ,
       60.  , 25.  , 14.  , 19.  , 18.  , 15.  , 31.  ,  4.  , 24.  ,
       25.  , 60.  , 52.  , 44.  , 24.  , 49.  , 42.  , 18.  , 35.  ,
       18.  , 25.  , 26.  , 39.  , 45.  , 42.  , 22.  , 24.  , 24.  ,
       24.  , 48.  , 29.  , 52.  , 19.  , 38.  , 27.  , 24.  , 33.  ,
        6.  , 17.  , 34.  , 50.  , 27.  , 20.  , 30.  , 24.  , 25.  ,
       25.  , 29.  , 11.  , 24.  , 23.  , 23.  , 28.5 , 48.  , 35.  ,
       24.  , 24.  , 24.  , 36.  , 21.  , 24.  , 31.  , 70.  , 16.  ,
       30.  , 19.  , 31.  ,  4.  ,  6.  , 33.  , 23.  , 48.  ,  0.67,
       28.  , 18.  , 34.  , 33.  , 24.  , 41.  , 20.  , 36.  , 16.  ,
       51.  , 24.  , 30.5 , 24.  , 32.  , 24.  , 48.  , 57.  , 24.  ,
       54.  , 18.  , 24.  ,  5.  , 24.  , 43.  , 13.  , 17.  , 29.  ,
       24.  , 25.  , 25.  , 18.  ,  8.  ,  1.  , 46.  , 24.  , 16.  ,
       24.  , 24.  , 25.  , 39.  , 49.  , 31.  , 30.  , 30.  , 34.  ,
       31.  , 11.  ,  0.42, 27.  , 31.  , 39.  , 18.  , 39.  , 33.  ,
       26.  , 39.  , 35.  ,  6.  , 30.5 , 24.  , 23.  , 31.  , 43.  ,
       10.  , 52.  , 27.  , 38.  , 27.  ,  2.  , 24.  , 24.  ,  1.  ,
       24.  , 62.  , 15.  ,  0.83, 24.  , 23.  , 18.  , 39.  , 21.  ,
       24.  , 32.  , 24.  , 20.  , 16.  , 30.  , 34.5 , 17.  , 42.  ,
       24.  , 35.  , 28.  , 24.  ,  4.  , 74.  ,  9.  , 16.  , 44.  ,
       18.  , 45.  , 51.  , 24.  , 24.  , 41.  , 21.  , 48.  , 24.  ,
       24.  , 42.  , 27.  , 31.  , 24.  ,  4.  , 26.  , 47.  , 33.  ,
       47.  , 28.  , 15.  , 20.  , 19.  , 24.  , 56.  , 25.  , 33.  ,
       22.  , 28.  , 25.  , 39.  , 27.  , 19.  , 24.  , 26.  , 32.  ])

In [60]:
data5 = data.copy()

In [61]:
data5.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

* 결측값이 30% ~ 50%일 때 KNN 최근접이웃법

In [62]:
from sklearn.impute import KNNImputer

In [66]:
knn_imp = KNNImputer(n_neighbors=5)
data5['Age'] = knn_imp.fit_transform(data5[['Age']])[:, 0]

In [68]:
data5.loc[na_idx]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,29.699118,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,29.699118,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,29.699118,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,29.699118,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,29.699118,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,29.699118,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,29.699118,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,29.699118,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,29.699118,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,NaN,S

# 깊은 복사, 얕은 복사

In [69]:
data.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [71]:
# data를 copy()를 이용해서 복사
data_copyed = data.copy()
# data를 다른 변수에 재할당
data_reassigned = data

In [70]:
data['Age'].isna().sum()

np.int64(177)

In [72]:
data_reassigned['Age'] = data_reassigned['Age'].fillna(28)

In [73]:
data_reassigned['Age'].isna().sum()

np.int64(0)

In [74]:
data['Age'].isna().sum()

np.int64(0)

In [75]:
data.loc[na_idx]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
5,6,0,3,"Moran, Mr. James",male,28.0,0,0,330877,8.4583,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,28.0,0,0,244373,13.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,28.0,0,0,2649,7.2250,NaN,C
26,27,0,3,"Emir, Mr. Farred Chehab",male,28.0,0,0,2631,7.2250,NaN,C
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,28.0,0,0,330959,7.8792,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,28.0,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,28.0,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,28.0,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,28.0,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,NaN,S

# 실제 메모상의 주소를 출력 id()

In [76]:
print("data의 메모리 주소: ", id(data))
print("data_reassigned의 메모리 주소: ", id(data_reassigned))
print("data_reassigned의 메모리 주소: ", id(data_copyed))

data의 메모리 주소:  2093904340256
data_reassigned의 메모리 주소:  2093904340256
data_reassigned의 메모리 주소:  2093943472032

In [77]:
data_copyed.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [78]:
new_df = data_copyed[['Survived', 'Pclass', 'Name']]
print('data_copyed: ', id(data_copyed))
print('new_df: ', id(new_df))

data_copyed:  2093943472032
new_df:  2093943575840

In [80]:
loc_result = data_copyed.loc[data_copyed['Age'] > 50, ['Name', 'Age']]
slice_result = data_copyed[data_copyed['Age'] > 50][['Name', 'Age']]

In [81]:
loc_result

                                                  Name   Age
6                              McCarthy, Mr. Timothy J  54.0
11                            Bonnell, Miss. Elizabeth  58.0
15                    Hewlett, Mrs. (Mary D Kingcome)   55.0
33                               Wheadon, Mr. Edward H  66.0
54                      Ostby, Mr. Engelhart Cornelius  65.0
..                                                 ...   ...
820  Hays, Mrs. Charles Melville (Clara Jennings Gr...  52.0
829          Stone, Mrs. George Nelson (Martha Evelyn)  62.0
851                                Svensson, Mr. Johan  74.0
857                             Daly, Mr. Peter Denis   51.0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0

[64 rows x 2 columns]

In [82]:
slice_result

                                                  Name   Age
6                              McCarthy, Mr. Timothy J  54.0
11                            Bonnell, Miss. Elizabeth  58.0
15                    Hewlett, Mrs. (Mary D Kingcome)   55.0
33                               Wheadon, Mr. Edward H  66.0
54                      Ostby, Mr. Engelhart Cornelius  65.0
..                                                 ...   ...
820  Hays, Mrs. Charles Melville (Clara Jennings Gr...  52.0
829          Stone, Mrs. George Nelson (Martha Evelyn)  62.0
851                                Svensson, Mr. Johan  74.0
857                             Daly, Mr. Peter Denis   51.0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0

[64 rows x 2 columns]

In [83]:
print('data_copyed:', id(data_copyed))
print('loc_result:', id(loc_result))
print('slice_result:', id(slice_result))

data_copyed: 2093943472032
loc_result: 2093955981472
slice_result: 2093955982336

In [85]:
data.isna().sum() / len(data) * 100

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age             0.000000
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

In [86]:
data.drop('Cabin', axis=1, inplace=True)

In [87]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

# 카테고리 변수의 경우 최빈값 .mode()를 이용해 결측값 처리

In [88]:
Embarked_idx = data[data['Embarked'].isna()].index

In [89]:
data['Embarked'] = data['Embarked'].fillna(data['Embarked'].mode()[0])

In [90]:
data.loc[Embarked_idx]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
61,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0,S

In [92]:
data.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64