# KNN_SVM_프로모션_효율예측분석

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import koreanize_matplotlib

In [2]:
mem = pd.read_csv("./data/member.csv")
tran = pd.read_csv("./data/transaction.csv")

* 쇼핑몰 고객 데이터, 프로모션 쿠폰을 발행하고 사용 여부 데이터 수집
* mem : 고객id, 최근 방문일, 사는 지역, 추천여부, 주요접속채널, 쿠폰사용여부(target)
* tran : 고객id, 구매수량, 총 구매금액
* 전통적 마케팅 분석 방법 RFM 기법을 활용해 고객 데이터에서 파생변수 생성 후 분석
* R(Recency) : 현재일 - 최근 구매일
* F(Frequency) : 구매빈도
* M(Monetary) : 구매 금액
* 종속변수 : conversion => 고객이 프로모션에 반응 했는가? 1 = yes, 0 = no

In [3]:
mem.head(2)

       id  recency   zip_code  is_referral channel  conversion
0  906145       10  Surburban            0   Phone           0
1  184478        6      Rural            1     Web           0

In [4]:
tran.head(2)

       id  num_item  total_amount
0  906145         5         34000
1  906145         1         27000

In [5]:
mem.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64000 entries, 0 to 63999
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           64000 non-null  int64
 1   recency      64000 non-null  int64
 2   zip_code     64000 non-null  object
 3   is_referral  64000 non-null  int64
 4   channel      64000 non-null  object
 5   conversion   64000 non-null  int64
dtypes: int64(4), object(2)
memory usage: 2.9+ MB

In [6]:
tran.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196836 entries, 0 to 196835
Data columns (total 3 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            196836 non-null  int64
 1   num_item      196836 non-null  int64
 2   total_amount  196836 non-null  int64
dtypes: int64(3)
memory usage: 4.5 MB

In [7]:
mem.describe()

                  id       recency   is_referral    conversion
count   64000.000000  64000.000000  64000.000000  64000.000000
mean   550694.137797      5.763734      0.502250      0.146781
std    259105.689773      3.507592      0.499999      0.353890
min    100001.000000      1.000000      0.000000      0.000000
25%    326772.000000      2.000000      0.000000      0.000000
50%    551300.000000      6.000000      1.000000      0.000000
75%    774914.500000      9.000000      1.000000      0.000000
max    999997.000000     12.000000      1.000000      1.000000

In [8]:
tran.describe()

                  id       num_item   total_amount
count  196836.000000  196836.000000  196836.000000
mean   550557.552932       3.078365   21837.102969
std    259254.795613       1.478408    8218.005565
min    100001.000000       1.000000    8000.000000
25%    326719.000000       2.000000   15000.000000
50%    550918.000000       3.000000   22000.000000
75%    774916.000000       4.000000   29000.000000
max    999997.000000       6.000000   38000.000000

# KNN, SVM