# 하나은행에서 환율조회 부분 찾아서 selenium으로 열기
* 날짜 입력부분 찾아 날짜 넣기
* 조회 버튼 찾아 버튼 클릭하기
* 조회된 데이터를 pd.read_html을 이용해 dataframe으로 만들기
* 데이터 프레임에 조회 날짜 컬럼 만들어서 날짜 추가하기

In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import pandas as pd

options = Options()
options.add_experimental_option("detach", True)
options.add_argument("start-maximized")
options.add_argument("Chrome/135.0.0.0")
options.add_argument("lang=ko_KR")

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
    )
driver.get("https://www.kebhana.com/cms/rate/index.do?contentUrl=/cms/rate/wpfxd651_01i.do")

In [2]:
# 날짜 입력
date_input = driver.find_element(By.CSS_SELECTOR, "#tmpInqStrDt")
date_input.clear()
date_input.send_keys("20250408")
date_input.send_keys(Keys.ENTER)

# 조회버튼 클릭
search_button = driver.find_element(By.CSS_SELECTOR, "#HANA_CONTENTS_DIV > div.btnBoxCenter > a")
search_button.click()

In [3]:
from io import StringIO

In [4]:
df = pd.read_html(StringIO(driver.find_element(By.CSS_SELECTOR, ".tblBasic.leftNone").get_attribute("outerHTML")))[0]
df

                 통화       현찰                              송금           \
                 통화     사실 때            파실 때            보낼 때     받을 때
                 통화       환율 Spread       환율 Spread     보낼 때     받을 때
0            미국 USD  1512.51   1.75  1460.49   1.75  1501.00  1472.00
1      일본 JPY (100)  1036.35   1.75  1000.71   1.75  1028.51  1008.55
2            유로 EUR  1663.21   1.99  1598.31   1.99  1647.06  1614.46
3            중국 CNY   210.70   5.00   190.64   5.00   202.67   198.67
4            홍콩 HKD   195.05   1.97   187.53   1.97   193.20   189.38
5            태국 THB    44.71   5.00    40.04   6.00    43.01    42.17
6            대만 TWD    50.73  13.10    40.38  10.00     0.00     0.00
7           필리핀 PHP    28.41  10.00    23.72   8.20    26.08    25.58
8          싱가포르 SGD  1120.61   1.99  1076.89   1.99  1109.73  1087.77
9            호주 AUD   902.57   1.97   867.71   1.97   893.99   876.29
10    베트남 VND (100)     6.40  11.80     5.06  11.80     5.78     5.68
11           영국 GBP  1937.55   1.97  1862.69   1.97  1919.12  1881.12
12          캐나다 CAD  1063.19   1.97  1022.11   1.97  1053.07  1032.23
13        말레이시아 MYR   355.49   7.40   306.51   7.40     0.00   327.69
14          러시아 RUB    18.96   9.50    14.29  17.50    17.92    16.72
15        남아공화국 ZAR    81.31   8.00    69.27   8.00    76.19    74.39
16         노르웨이 NOK   140.30   3.30   128.08   5.70   137.17   134.47
17         뉴질랜드 NZD   837.62   1.97   805.26   1.97   829.65   813.23
18          덴마크 DKK   225.62   3.30   205.98   5.70   220.60   216.24
19          멕시코 MXN    78.78  10.50    63.82  10.50    72.01    70.59
20           몽골 MNT     0.00   0.00     0.00   0.00     0.00     0.00
21          바레인 BHD  4195.87   6.40  3628.02   8.00  3982.92  3904.06
22        방글라데시 BDT     0.00   0.00     0.00   0.00     0.00     0.00
23          브라질 BRL   272.32  10.20   222.41  10.00     0.00   244.16
24         브루나이 BND  1142.70   4.00  1032.83   6.00     0.00     0.00
25      사우디아라비아 SAR   420.93   6.30   368.67   6.90   399.94   392.04
26         스리랑카 LKR     0.00   0.00     0.00   0.00     0.00     0.00
27          스웨덴 SEK   153.51   3.30   140.14   5.70   150.09   147.13
28          스위스 CHF  1791.60   1.97  1722.38   1.97  1774.55  1739.43
29    아랍에미리트공화국 AED   426.95   5.50   376.78   6.90   408.74   400.66
30          알제리 DZD     0.00   0.00     0.00   0.00     0.00     0.00
31           오만 OMR  4131.41   7.00  3590.87   7.00     0.00     0.00
32          요르단 JOD  2283.20   8.90  1928.89   8.00     0.00     0.00
33         이스라엘 ILS   432.63  10.00   361.84   8.00     0.00     0.00
34          이집트 EGP     0.00   0.00     0.00   0.00     0.00     0.00
35           인도 INR     0.00   0.00     0.00   0.00    17.42    17.04
36  인도네시아 IDR (100)     9.71  10.00     7.95  10.00     8.91     8.75
37           체코 CZK    70.18   8.50    58.87   9.00    65.40    63.98
38           칠레 CLP     1.63  10.00     1.35  10.00     0.00     0.00
39        카자흐스탄 KZT     0.00   0.00     0.00   0.00     0.00     0.00
40          카타르 QAR     0.00   0.00     0.00   0.00     0.00     0.00
41           케냐 KES     0.00   0.00     0.00   0.00     0.00     0.00
42         콜롬비아 COP     0.00   0.00     0.00   0.00     0.00     0.00
43         쿠웨이트 KWD  5138.00   6.50  4438.47   8.00  4872.66  4776.18
44         탄자니아 TZS     0.00   0.00     0.00   0.00     0.00     0.00
45         튀르키예 TRY     0.00   0.00     0.00   0.00    39.63    38.77
46         파키스탄 PKR     0.00   0.00     0.00   0.00     0.00     0.00
47          폴란드 PLN   412.32   8.00   351.24   8.00   385.97   377.59
48          헝가리 HUF     4.37   9.30     3.68   8.00     4.04     3.96
49           네팔 NPR     0.00   0.00     0.00   0.00     0.00     0.00
50          마카오 MOP     0.00   0.00     0.00   0.00     0.00     0.00
51         캄보디아 KHR     0.00   0.00     0.00   0.00     0.00     0.00
52           피지 FJD     0.00   0.00     0.00   0.00     0.00     0.00
53          리비아 LYD     0.00   0.00     0.00   0.00   269.96   264.62
54         루마니아 RON     0.00   0.00     0.00   0.00   331.26   324.06
55          미얀마 MMK     0.00   0.00     0.00   0.00     0.00     0.00
56        에티오피아 ETB     0.00   0.00     0.00   0.00     0.00     0.00
57       우즈베키스탄 UZS     0.00   0.00     0.00   0.00     0.00     0.00

   외화 수표 파실때   매매 기준율     환가 료율  미화 환산율
   외화 수표 파실때   매매 기준율     환가 료율  미화 환산율
   외화 수표 파실때   매매 기준율     환가 료율  미화 환산율
0    1469.47  1486.50   6.15079  1.0000
1    1007.90  1018.53   2.60318  0.6852
2    1612.51  1630.76   4.31600  1.0970
3       0.00   200.67   4.43712  0.1350
4     189.11   191.29   5.74800  0.1287
5      42.13    42.59   4.03366  0.0287
6       0.00    44.86   3.58766  0.0302
7       0.00    25.83   7.52400  0.0174
8    1086.49  1098.75   4.76033  0.7392
9     874.79   885.14   6.22766  0.5955
10      0.00     5.73   6.61166  0.0039
11   1877.72  1900.12   6.53300  1.2783
12   1030.85  1042.65   4.76900  0.7014
13      0.00   331.00   5.26066  0.2227
14      0.00    17.32   2.97500  0.0117
15      0.00    75.29   9.61100  0.0506
16    134.23   135.82   6.44133  0.0914
17    811.95   821.44   5.71166  0.5526
18    215.97   218.42   4.60800  0.1469
19      0.00    71.30  11.68300  0.0480
20      0.00     0.42  13.47500  0.0003
21   3895.56  3943.49   7.76900  2.6529
22      0.00    12.23  12.17370  0.0082
23      0.00   247.12  14.67000  0.1662
24      0.00  1098.75   4.67500  0.7392
25    391.22   395.99   7.47533  0.2664
26      0.00     4.96  11.50000  0.0033
27    146.95   148.61   4.40666  0.1000
28   1738.30  1756.99   2.32000  1.1820
29    400.10   404.70   5.07500  0.2723
30      0.00    11.13   5.97500  0.0075
31      0.00  3861.14   4.45500  2.5975
32      0.00  2096.61   8.73900  1.4104
33      0.00   393.30   6.56500  0.2646
34      0.00    28.99   5.97500  0.0195
35      0.00    17.23   9.06800  0.0116
36      8.74     8.83   8.42166  0.0059
37      0.00    64.69   5.73366  0.0435
38      0.00     1.49   6.12200  0.0010
39      0.00     2.87  16.97500  0.0019
40      0.00   407.82   3.35500  0.2743
41      0.00    11.48   9.78333  0.0077
42      0.00     0.34   0.00000  0.0002
43   4769.94  4824.42   4.65766  3.2455
44      0.00     0.55  10.27500  0.0004
45      0.00    39.20  49.80833  0.0264
46      0.00     5.30  18.24833  0.0036
47      0.00   381.78   8.13933  0.2568
48      0.00     4.00   8.44966  0.0027
49      0.00    10.77   0.00000  0.0072
50      0.00   185.58   0.00000  0.1248
51      0.00     0.37   0.00000  0.0002
52      0.00   633.84   0.00000  0.4264
53      0.00   267.29   0.00000  0.1798
54      0.00   327.66   7.75800  0.2204
55      0.00     0.71   0.00000  0.0005
56      0.00    11.24   0.00000  0.0076
57      0.00     0.11   0.00000  0.0001

# 날짜 생성하기
* 1995-01-03 ~ 어제까지(2025-04-08) 날짜 생성하기
* 평일만 날짜 생성
* 날짜리스트에 모든 날짜 저장

In [5]:
import datetime

In [6]:
current_date = datetime.date(2025, 4, 8)

In [7]:
current_date

datetime.date(2025, 4, 8)

In [10]:
# 날짜 데이터 타입은 논리 연산(비교) 가능
current_date < day

True

In [9]:
# weekday() - 월:0, 화:1, 수:2, 목:3, 금:4, 토:5, 일:6
# datetime.timedelta로 날짜 증감 가능
for days in range(1, 10):
#     print(current_date + datetime.timedelta(days=days)) 
    day = current_date + datetime.timedelta(days=days)
    if day.weekday() < 5:
        print(day, day.weekday())

2025-04-09 2
2025-04-10 3
2025-04-11 4
2025-04-14 0
2025-04-15 1
2025-04-16 2
2025-04-17 3

# 시작일과 끝일을 입력해서 평일만 생성하기

In [20]:
start_date = datetime.date(2025, 4, 1) 
end_date = datetime.date(2025, 4, 8)

In [21]:
date_list = []
while start_date <= end_date:
    # 평일인지 필터링
    if start_date.weekday() < 5:
        date_list.append(start_date)
    start_date += datetime.timedelta(days=1)
date_list

[datetime.date(2025, 4, 1),
 datetime.date(2025, 4, 2),
 datetime.date(2025, 4, 3),
 datetime.date(2025, 4, 4),
 datetime.date(2025, 4, 7),
 datetime.date(2025, 4, 8)]

In [25]:
print(str(date_list[0]).replace("-", ""))

20250401

# 코드 합쳐서 전체 날짜 데이터 추출하기

In [ ]:
# list -> 1개의 문자열로 합치는 함수 join()
# 문자열 -> list로 만드는 함수 split()
# 중복된 자료 제거 : set 집합자료형
# set 자료형은 순서가 없음

In [50]:
# 데이터 프레임 컬럼명 바꾸기
def new_col(df):
    new_cols = []
    for col in df.columns:
        if col[0] == col[1] == col[2]:
            new_cols.append(col[0].replace(" ", "_"))
        else:
            new_cols.append(" ".join(col).strip().replace(" ", "_"))
    return new_cols

In [51]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import datetime
from io import StringIO
import time
from ex_dbio import to_ex_db

options = Options()
options.add_experimental_option("detach", True)
options.add_argument("start-maximized")
options.add_argument("Chrome/135.0.0.0")
options.add_argument("lang=ko_KR")

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
    )
url = "https://www.kebhana.com/cms/rate/index.do?contentUrl=/cms/rate/wpfxd651_01i.do"
driver.get(url)

wait = WebDriverWait(driver, 10)

# 시작일과 끝일 입력해서 날짜 리스트 생성
start_date = datetime.date(2025, 4, 1) 
end_date = datetime.date(2025, 4, 2) 

date_list = []
while start_date <= end_date:
    # 평일인지 필터링
    if start_date.weekday() < 5:
        date_list.append(start_date)
    start_date += datetime.timedelta(days=1)
date_list

for date in date_list:
    # 날짜 입력
    date_input = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "#tmpInqStrDt")))
    date_input.clear()
    date_input.send_keys(str(date).replace("-", ""))
    date_input.send_keys(Keys.ENTER)

    # 조회버튼 클릭
    search_button = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "#HANA_CONTENTS_DIV > div.btnBoxCenter > a")))
    search_button.click()

    time.sleep(2)
    
    df = pd.read_html(StringIO(driver.find_element(By.CSS_SELECTOR, ".tblBasic.leftNone").get_attribute("outerHTML")))[0]
    df['date'] = date
    new_columns = new_col(df)
    df.columns = new_columns
    df = df[['date', '통화', '현찰_사실_때_환율', '현찰_사실_때_Spread', '현찰_파실_때_환율', '현찰_파실_때_Spread',
       '송금_보낼_때_보낼_때', '송금_받을_때_받을_때', '외화_수표_파실때', '매매_기준율', '환가_료율',
       '미화_환산율']]
    display(df)
    to_ex_db(df)

,date,통화,현찰_사실_때_환율,현찰_사실_때_Spread,현찰_파실_때_환율,현찰_파실_때_Spread,송금_보낼_때_보낼_때,송금_받을_때_받을_때,외화_수표_파실때,매매_기준율,환가_료율,미화_환산율
0,2025-04-01,미국 USD,1497.25,1.75,1445.75,1.75,1485.90,1457.10,1454.58,1471.50,6.16937,1.0000
1,2025-04-01,일본 JPY (100),999.60,1.75,965.22,1.75,992.03,972.79,972.17,982.41,2.58136,0.6676
2,2025-04-01,유로 EUR,1620.77,1.99,1557.53,1.99,1605.04,1573.26,1571.36,1589.15,4.31900,1.0800
3,2025-04-01,중국 CNY,212.25,5.00,192.05,5.00,204.17,200.13,0.00,202.15,3.91894,0.1374
4,2025-04-01,홍콩 HKD,192.82,1.97,185.38,1.97,190.99,187.21,186.94,189.10,5.83533,0.1285
5,2025-04-01,태국 THB,45.18,5.00,40.45,6.00,43.46,42.60,42.56,43.03,4.07533,0.0292
6,2025-04-01,대만 TWD,50.10,13.10,39.87,10.00,0.00,0.00,0.00,44.30,3.58700,0.0301
7,2025-04-01,필리핀 PHP,28.29,10.00,23.62,8.20,25.97,25.47,0.00,25.72,7.30900,0.0175
8,2025-04-01,싱가포르 SGD,1116.82,1.99,1073.24,1.99,1105.98,1084.08,1082.79,1095.03,4.80033,0.7442
9,2025-04-01,호주 AUD,943.28,1.97,906.84,1.97,934.31,915.81,914.24,925.06,6.21466,0.6287
10,2025-04-01,베트남 VND (100),6.42,11.80,5.08,11.80,5.80,5.70,0.00,5.75,6.64833,0.0039
11,2025-04-01,영국 GBP,1939.75,1.97,1864.81,1.97,1921.30,1883.26,1879.86,1902.28,6.53833,1.2927
12,2025-04-01,캐나다 CAD,1049.58,1.97,1009.04,1.97,1039.60,1019.02,1017.65,1029.31,4.81500,0.6995
13,2025-04-01,말레이시아 MYR,356.14,7.40,307.08,7.40,0.00,328.30,0.00,331.61,5.26033,0.2254
14,2025-04-01,러시아 RUB,19.06,9.50,14.37,17.50,18.01,16.81,0.00,17.41,2.97500,0.0118
15,2025-04-01,남아공화국 ZAR,86.05,8.00,73.31,8.00,80.63,78.73,0.00,79.68,9.66900,0.0541
16,2025-04-01,노르웨이 NOK,145.34,3.30,132.69,5.70,142.10,139.30,139.05,140.70,6.43366,0.0956
17,2025-04-01,뉴질랜드 NZD,856.55,1.97,823.47,1.97,848.41,831.61,830.28,840.01,5.78700,0.5709
18,2025-04-01,덴마크 DKK,220.00,3.30,200.85,5.70,215.10,210.86,210.59,212.98,4.68300,0.1447
19,2025-04-01,멕시코 MXN,79.97,10.50,64.79,10.50,73.10,71.66,0.00,72.38,11.54200,0.0492
20,2025-04-01,몽골 MNT,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.42,13.47500,0.0003
21,2025-04-01,바레인 BHD,4153.20,6.40,3591.12,8.00,3942.42,3864.36,3855.95,3903.39,7.76500,2.6527
22,2025-04-01,방글라데시 BDT,0.00,0.00,0.00,0.00,0.00,0.00,0.00,12.11,12.18010,0.0082
23,2025-04-01,브라질 BRL,285.39,10.20,233.09,10.00,0.00,255.88,0.00,258.98,14.16100,0.1760
24,2025-04-01,브루나이 BND,1138.83,4.00,1029.33,6.00,0.00,0.00,0.00,1095.03,4.77500,0.7442
25,2025-04-01,사우디아라비아 SAR,416.96,6.30,365.19,6.90,396.17,388.33,387.52,392.25,7.46766,0.2666
26,2025-04-01,스리랑카 LKR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,4.97,11.50000,0.0034
27,2025-04-01,스웨덴 SEK,151.85,3.30,138.63,5.70,148.47,145.53,145.36,147.00,4.40566,0.0999
28,2025-04-01,스위스 CHF,1697.86,1.97,1632.26,1.97,1681.71,1648.41,1647.32,1665.06,2.36633,1.1315
29,2025-04-01,아랍에미리트공화국 AED,422.67,5.50,373.00,6.90,404.64,396.64,396.08,400.64,5.07500,0.2723
30,2025-04-01,알제리 DZD,0.00,0.00,0.00,0.00,0.00,0.00,0.00,10.97,3.97500,0.0075
31,2025-04-01,오만 OMR,4089.83,7.00,3554.73,7.00,0.00,0.00,0.00,3822.28,4.29500,2.5975
32,2025-04-01,요르단 JOD,2260.17,8.90,1909.43,8.00,0.00,0.00,0.00,2075.46,8.73900,1.4104
33,2025-04-01,이스라엘 ILS,438.68,10.00,366.90,8.00,0.00,0.00,0.00,398.80,6.56500,0.2710
34,2025-04-01,이집트 EGP,0.00,0.00,0.00,0.00,0.00,0.00,0.00,29.10,3.97500,0.0198
35,2025-04-01,인도 INR,0.00,0.00,0.00,0.00,17.38,17.00,0.00,17.19,9.07966,0.0117
36,2025-04-01,인도네시아 IDR (100),9.79,10.00,8.01,10.00,8.98,8.82,8.81,8.90,8.42166,0.0060
37,2025-04-01,체코 CZK,69.13,8.50,57.99,9.00,64.42,63.02,0.00,63.72,5.81300,0.0433
38,2025-04-01,칠레 CLP,1.70,10.00,1.40,10.00,0.00,0.00,0.00,1.55,6.24300,0.0011
39,2025-04-01,카자흐스탄 KZT,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2.92,16.97500,0.0020
40,2025-04-01,카타르 QAR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,403.68,3.35500,0.2743
41,2025-04-01,케냐 KES,0.00,0.00,0.00,0.00,0.00,0.00,0.00,11.38,9.72500,0.0077
42,2025-04-01,콜롬비아 COP,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.35,0.00000,0.0002
43,2025-04-01,쿠웨이트 KWD,5081.71,6.50,4389.84,8.00,4819.27,4723.85,4717.74,4771.56,4.61200,3.2427
44,2025-04-01,탄자니아 TZS,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.56,9.82333,0.0004
45,2025-04-01,튀르키예 TRY,0.00,0.00,0.00,0.00,39.17,38.33,0.00,38.75,47.74166,0.0263
46,2025-04-01,파키스탄 PKR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,5.25,18.37500,0.0036
47,2025-04-01,폴란드 PLN,410.29,8.00,349.51,8.00,384.07,375.73,0.00,379.90,8.13333,0.2582
48,2025-04-01,헝가리 HUF,4.31,9.30,3.64,8.00,3.99,3.91,0.00,3.95,8.46233,0.0027
49,2025-04-01,네팔 NPR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,10.76,0.00000,0.0073
50,2025-04-01,마카오 MOP,0.00,0.00,0.00,0.00,0.00,0.00,0.00,183.50,0.00000,0.1247
51,2025-04-01,캄보디아 KHR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.37,0.00000,0.0003
52,2025-04-01,피지 FJD,0.00,0.00,0.00,0.00,0.00,0.00,0.00,631.42,0.00000,0.4291
53,2025-04-01,리비아 LYD,0.00,0.00,0.00,0.00,307.31,301.23,0.00,304.27,0.00000,0.2068
54,2025-04-01,루마니아 RON,0.00,0.00,0.00,0.00,322.78,315.76,0.00,319.27,7.76733,0.2170
55,2025-04-01,미얀마 MMK,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.70,0.00000,0.0005
56,2025-04-01,에티오피아 ETB,0.00,0.00,0.00,0.00,0.00,0.00,0.00,11.12,0.00000,0.0076
57,2025-04-01,우즈베키스탄 UZS,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.11,0.00000,0.0001

,date,통화,현찰_사실_때_환율,현찰_사실_때_Spread,현찰_파실_때_환율,현찰_파실_때_Spread,송금_보낼_때_보낼_때,송금_받을_때_받을_때,외화_수표_파실때,매매_기준율,환가_료율,미화_환산율
0,2025-04-02,미국 USD,1493.18,1.75,1441.82,1.75,1481.80,1453.20,1450.69,1467.50,6.16896,1.0000
1,2025-04-02,일본 JPY (100),1007.50,1.75,972.86,1.75,999.88,980.48,979.85,990.18,2.58136,0.6747
2,2025-04-02,유로 EUR,1618.38,1.99,1555.24,1.99,1602.67,1570.95,1569.05,1586.81,4.33300,1.0813
3,2025-04-02,중국 CNY,209.71,5.00,189.75,5.00,201.72,197.74,0.00,199.73,4.03924,0.1361
4,2025-04-02,홍콩 HKD,192.26,1.97,184.84,1.97,190.43,186.67,186.40,188.55,5.82466,0.1285
5,2025-04-02,태국 THB,44.75,5.00,40.07,6.00,43.04,42.20,42.16,42.62,4.06700,0.0290
6,2025-04-02,대만 TWD,49.92,13.10,39.73,10.00,0.00,0.00,0.00,44.14,3.58633,0.0301
7,2025-04-02,필리핀 PHP,28.22,10.00,23.56,8.20,25.91,25.41,0.00,25.66,7.30900,0.0175
8,2025-04-02,싱가포르 SGD,1108.63,1.99,1065.37,1.99,1097.87,1076.13,1074.85,1087.00,4.79033,0.7407
9,2025-04-02,호주 AUD,933.23,1.97,897.19,1.97,924.36,906.06,904.51,915.21,6.21633,0.6237
10,2025-04-02,베트남 VND (100),6.41,11.80,5.07,11.80,5.79,5.69,0.00,5.74,6.63833,0.0039
11,2025-04-02,영국 GBP,1943.31,1.97,1868.23,1.97,1924.82,1886.72,1883.31,1905.77,6.53666,1.2987
12,2025-04-02,캐나다 CAD,1046.33,1.97,1005.91,1.97,1036.38,1015.86,1014.50,1026.12,4.80266,0.6992
13,2025-04-02,말레이시아 MYR,353.86,7.40,305.10,7.40,0.00,326.19,0.00,329.48,5.26033,0.2245
14,2025-04-02,러시아 RUB,19.07,9.50,14.38,17.50,18.02,16.82,0.00,17.42,2.97500,0.0119
15,2025-04-02,남아공화국 ZAR,83.67,8.00,71.29,8.00,78.40,76.56,0.00,77.48,9.66233,0.0528
16,2025-04-02,노르웨이 NOK,145.17,3.30,132.53,5.70,141.94,139.14,138.89,140.54,6.43333,0.0958
17,2025-04-02,뉴질랜드 NZD,851.97,1.97,819.07,1.97,843.87,827.17,825.85,835.52,5.77166,0.5693
18,2025-04-02,덴마크 DKK,219.68,3.30,200.55,5.70,214.79,210.55,210.28,212.67,4.66533,0.1449
19,2025-04-02,멕시코 MXN,79.76,10.50,64.62,10.50,72.91,71.47,0.00,72.19,11.66900,0.0492
20,2025-04-02,몽골 MNT,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.42,13.47500,0.0003
21,2025-04-02,바레인 BHD,4141.91,6.40,3581.36,8.00,3931.70,3853.86,3845.47,3892.78,7.76600,2.6527
22,2025-04-02,방글라데시 BDT,0.00,0.00,0.00,0.00,0.00,0.00,0.00,12.08,12.18010,0.0082
23,2025-04-02,브라질 BRL,285.42,10.20,233.11,10.00,0.00,255.91,0.00,259.01,14.29800,0.1765
24,2025-04-02,브루나이 BND,1130.48,4.00,1021.78,6.00,0.00,0.00,0.00,1087.00,4.67500,0.7407
25,2025-04-02,사우디아라비아 SAR,415.81,6.30,364.18,6.90,395.08,387.26,386.45,391.17,7.47566,0.2666
26,2025-04-02,스리랑카 LKR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,4.96,11.50000,0.0034
27,2025-04-02,스웨덴 SEK,152.57,3.30,139.29,5.70,149.17,146.23,146.06,147.70,4.40633,0.1006
28,2025-04-02,스위스 CHF,1699.20,1.97,1633.56,1.97,1683.04,1649.72,1648.63,1666.38,2.36233,1.1355
29,2025-04-02,아랍에미리트공화국 AED,421.50,5.50,371.97,6.90,403.52,395.54,394.98,399.53,5.07500,0.2723
30,2025-04-02,알제리 DZD,0.00,0.00,0.00,0.00,0.00,0.00,0.00,10.96,3.97500,0.0075
31,2025-04-02,오만 OMR,4078.72,7.00,3545.06,7.00,0.00,0.00,0.00,3811.89,4.29500,2.5975
32,2025-04-02,요르단 JOD,2254.03,8.90,1904.24,8.00,0.00,0.00,0.00,2069.82,8.73900,1.4104
33,2025-04-02,이스라엘 ILS,434.69,10.00,363.57,8.00,0.00,0.00,0.00,395.18,6.56500,0.2693
34,2025-04-02,이집트 EGP,0.00,0.00,0.00,0.00,0.00,0.00,0.00,29.02,3.97500,0.0198
35,2025-04-02,인도 INR,0.00,0.00,0.00,0.00,17.36,16.98,0.00,17.17,9.07966,0.0117
36,2025-04-02,인도네시아 IDR (100),9.76,10.00,8.00,10.00,8.96,8.80,8.79,8.88,8.42166,0.0061
37,2025-04-02,체코 CZK,69.03,8.50,57.91,9.00,64.32,62.94,0.00,63.63,5.73366,0.0434
38,2025-04-02,칠레 CLP,1.69,10.00,1.39,10.00,0.00,0.00,0.00,1.54,6.17100,0.0010
39,2025-04-02,카자흐스탄 KZT,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2.92,16.97500,0.0020
40,2025-04-02,카타르 QAR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,402.58,3.35500,0.2743
41,2025-04-02,케냐 KES,0.00,0.00,0.00,0.00,0.00,0.00,0.00,11.35,9.75833,0.0077
42,2025-04-02,콜롬비아 COP,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.35,0.00000,0.0002
43,2025-04-02,쿠웨이트 KWD,5070.84,6.50,4380.46,8.00,4808.97,4713.75,4707.66,4761.36,4.61200,3.2445
44,2025-04-02,탄자니아 TZS,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.56,10.05666,0.0004
45,2025-04-02,튀르키예 TRY,0.00,0.00,0.00,0.00,39.13,38.29,0.00,38.71,48.34166,0.0264
46,2025-04-02,파키스탄 PKR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,5.24,18.37500,0.0036
47,2025-04-02,폴란드 PLN,409.96,8.00,349.24,8.00,383.77,375.43,0.00,379.60,8.14000,0.2587
48,2025-04-02,헝가리 HUF,4.31,9.30,3.64,8.00,3.99,3.91,0.00,3.95,8.46133,0.0027
49,2025-04-02,네팔 NPR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,10.73,0.00000,0.0073
50,2025-04-02,마카오 MOP,0.00,0.00,0.00,0.00,0.00,0.00,0.00,182.96,0.00000,0.1247
51,2025-04-02,캄보디아 KHR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.37,0.00000,0.0003
52,2025-04-02,피지 FJD,0.00,0.00,0.00,0.00,0.00,0.00,0.00,630.44,0.00000,0.4296
53,2025-04-02,리비아 LYD,0.00,0.00,0.00,0.00,306.47,300.41,0.00,303.44,0.00000,0.2068
54,2025-04-02,루마니아 RON,0.00,0.00,0.00,0.00,322.30,315.30,0.00,318.80,7.76766,0.2172
55,2025-04-02,미얀마 MMK,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.70,0.00000,0.0005
56,2025-04-02,에티오피아 ETB,0.00,0.00,0.00,0.00,0.00,0.00,0.00,11.15,0.00000,0.0076
57,2025-04-02,우즈베키스탄 UZS,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.11,0.00000,0.0001

In [45]:
df.columns = new_cols
df.columns

Index(['통화', '현찰_사실_때_환율', '현찰_사실_때_Spread', '현찰_파실_때_환율', '현찰_파실_때_Spread',
       '송금_보낼_때_보낼_때', '송금_받을_때_받을_때', '외화_수표_파실때', '매매_기준율', '환가_료율',
       '미화_환산율', 'date'],
      dtype='object')

In [47]:
# 데이터프레임 컬럼명 순서 바꾸기
df = df[['date', '통화', '현찰_사실_때_환율', '현찰_사실_때_Spread', '현찰_파실_때_환율', '현찰_파실_때_Spread',
       '송금_보낼_때_보낼_때', '송금_받을_때_받을_때', '외화_수표_파실때', '매매_기준율', '환가_료율',
       '미화_환산율']]
df

,date,통화,현찰_사실_때_환율,현찰_사실_때_Spread,현찰_파실_때_환율,현찰_파실_때_Spread,송금_보낼_때_보낼_때,송금_받을_때_받을_때,외화_수표_파실때,매매_기준율,환가_료율,미화_환산율
0,2025-04-02,미국 USD,1493.18,1.75,1441.82,1.75,1481.80,1453.20,1450.69,1467.50,6.16896,1.0000
1,2025-04-02,일본 JPY (100),1007.50,1.75,972.86,1.75,999.88,980.48,979.85,990.18,2.58136,0.6747
2,2025-04-02,유로 EUR,1618.38,1.99,1555.24,1.99,1602.67,1570.95,1569.05,1586.81,4.33300,1.0813
3,2025-04-02,중국 CNY,209.71,5.00,189.75,5.00,201.72,197.74,0.00,199.73,4.03924,0.1361
4,2025-04-02,홍콩 HKD,192.26,1.97,184.84,1.97,190.43,186.67,186.40,188.55,5.82466,0.1285
5,2025-04-02,태국 THB,44.75,5.00,40.07,6.00,43.04,42.20,42.16,42.62,4.06700,0.0290
6,2025-04-02,대만 TWD,49.92,13.10,39.73,10.00,0.00,0.00,0.00,44.14,3.58633,0.0301
7,2025-04-02,필리핀 PHP,28.22,10.00,23.56,8.20,25.91,25.41,0.00,25.66,7.30900,0.0175
8,2025-04-02,싱가포르 SGD,1108.63,1.99,1065.37,1.99,1097.87,1076.13,1074.85,1087.00,4.79033,0.7407
9,2025-04-02,호주 AUD,933.23,1.97,897.19,1.97,924.36,906.06,904.51,915.21,6.21633,0.6237
10,2025-04-02,베트남 VND (100),6.41,11.80,5.07,11.80,5.79,5.69,0.00,5.74,6.63833,0.0039
11,2025-04-02,영국 GBP,1943.31,1.97,1868.23,1.97,1924.82,1886.72,1883.31,1905.77,6.53666,1.2987
12,2025-04-02,캐나다 CAD,1046.33,1.97,1005.91,1.97,1036.38,1015.86,1014.50,1026.12,4.80266,0.6992
13,2025-04-02,말레이시아 MYR,353.86,7.40,305.10,7.40,0.00,326.19,0.00,329.48,5.26033,0.2245
14,2025-04-02,러시아 RUB,19.07,9.50,14.38,17.50,18.02,16.82,0.00,17.42,2.97500,0.0119
15,2025-04-02,남아공화국 ZAR,83.67,8.00,71.29,8.00,78.40,76.56,0.00,77.48,9.66233,0.0528
16,2025-04-02,노르웨이 NOK,145.17,3.30,132.53,5.70,141.94,139.14,138.89,140.54,6.43333,0.0958
17,2025-04-02,뉴질랜드 NZD,851.97,1.97,819.07,1.97,843.87,827.17,825.85,835.52,5.77166,0.5693
18,2025-04-02,덴마크 DKK,219.68,3.30,200.55,5.70,214.79,210.55,210.28,212.67,4.66533,0.1449
19,2025-04-02,멕시코 MXN,79.76,10.50,64.62,10.50,72.91,71.47,0.00,72.19,11.66900,0.0492
20,2025-04-02,몽골 MNT,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.42,13.47500,0.0003
21,2025-04-02,바레인 BHD,4141.91,6.40,3581.36,8.00,3931.70,3853.86,3845.47,3892.78,7.76600,2.6527
22,2025-04-02,방글라데시 BDT,0.00,0.00,0.00,0.00,0.00,0.00,0.00,12.08,12.18010,0.0082
23,2025-04-02,브라질 BRL,285.42,10.20,233.11,10.00,0.00,255.91,0.00,259.01,14.29800,0.1765
24,2025-04-02,브루나이 BND,1130.48,4.00,1021.78,6.00,0.00,0.00,0.00,1087.00,4.67500,0.7407
25,2025-04-02,사우디아라비아 SAR,415.81,6.30,364.18,6.90,395.08,387.26,386.45,391.17,7.47566,0.2666
26,2025-04-02,스리랑카 LKR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,4.96,11.50000,0.0034
27,2025-04-02,스웨덴 SEK,152.57,3.30,139.29,5.70,149.17,146.23,146.06,147.70,4.40633,0.1006
28,2025-04-02,스위스 CHF,1699.20,1.97,1633.56,1.97,1683.04,1649.72,1648.63,1666.38,2.36233,1.1355
29,2025-04-02,아랍에미리트공화국 AED,421.50,5.50,371.97,6.90,403.52,395.54,394.98,399.53,5.07500,0.2723
30,2025-04-02,알제리 DZD,0.00,0.00,0.00,0.00,0.00,0.00,0.00,10.96,3.97500,0.0075
31,2025-04-02,오만 OMR,4078.72,7.00,3545.06,7.00,0.00,0.00,0.00,3811.89,4.29500,2.5975
32,2025-04-02,요르단 JOD,2254.03,8.90,1904.24,8.00,0.00,0.00,0.00,2069.82,8.73900,1.4104
33,2025-04-02,이스라엘 ILS,434.69,10.00,363.57,8.00,0.00,0.00,0.00,395.18,6.56500,0.2693
34,2025-04-02,이집트 EGP,0.00,0.00,0.00,0.00,0.00,0.00,0.00,29.02,3.97500,0.0198
35,2025-04-02,인도 INR,0.00,0.00,0.00,0.00,17.36,16.98,0.00,17.17,9.07966,0.0117
36,2025-04-02,인도네시아 IDR (100),9.76,10.00,8.00,10.00,8.96,8.80,8.79,8.88,8.42166,0.0061
37,2025-04-02,체코 CZK,69.03,8.50,57.91,9.00,64.32,62.94,0.00,63.63,5.73366,0.0434
38,2025-04-02,칠레 CLP,1.69,10.00,1.39,10.00,0.00,0.00,0.00,1.54,6.17100,0.0010
39,2025-04-02,카자흐스탄 KZT,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2.92,16.97500,0.0020
40,2025-04-02,카타르 QAR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,402.58,3.35500,0.2743
41,2025-04-02,케냐 KES,0.00,0.00,0.00,0.00,0.00,0.00,0.00,11.35,9.75833,0.0077
42,2025-04-02,콜롬비아 COP,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.35,0.00000,0.0002
43,2025-04-02,쿠웨이트 KWD,5070.84,6.50,4380.46,8.00,4808.97,4713.75,4707.66,4761.36,4.61200,3.2445
44,2025-04-02,탄자니아 TZS,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.56,10.05666,0.0004
45,2025-04-02,튀르키예 TRY,0.00,0.00,0.00,0.00,39.13,38.29,0.00,38.71,48.34166,0.0264
46,2025-04-02,파키스탄 PKR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,5.24,18.37500,0.0036
47,2025-04-02,폴란드 PLN,409.96,8.00,349.24,8.00,383.77,375.43,0.00,379.60,8.14000,0.2587
48,2025-04-02,헝가리 HUF,4.31,9.30,3.64,8.00,3.99,3.91,0.00,3.95,8.46133,0.0027
49,2025-04-02,네팔 NPR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,10.73,0.00000,0.0073
50,2025-04-02,마카오 MOP,0.00,0.00,0.00,0.00,0.00,0.00,0.00,182.96,0.00000,0.1247
51,2025-04-02,캄보디아 KHR,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.37,0.00000,0.0003
52,2025-04-02,피지 FJD,0.00,0.00,0.00,0.00,0.00,0.00,0.00,630.44,0.00000,0.4296
53,2025-04-02,리비아 LYD,0.00,0.00,0.00,0.00,306.47,300.41,0.00,303.44,0.00000,0.2068
54,2025-04-02,루마니아 RON,0.00,0.00,0.00,0.00,322.30,315.30,0.00,318.80,7.76766,0.2172
55,2025-04-02,미얀마 MMK,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.70,0.00000,0.0005
56,2025-04-02,에티오피아 ETB,0.00,0.00,0.00,0.00,0.00,0.00,0.00,11.15,0.00000,0.0076
57,2025-04-02,우즈베키스탄 UZS,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.11,0.00000,0.0001